name: Flutter
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          version: 1.8.4
          channel: dev
      - run: flutter pub get
      - run: flutter test
      # If playstore, then build bundles are better
      - name: Build
        run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
      # TODO: probably gotta just make a docker image for the hub cli
      - name: Release
        # TODO: probably want to move the apks instead of giving them different alias text (since they download as their original file name)
        # TODO: probably want to build "FAT" apk also
        uses: docker://pentible/hub
        with:
          args: release create -m "Release ${{ github.sha }}" -a "build/app/outputs/apk/release/app-armeabi-v7a-release.apk#notes-armeabi-v7a.apk" -a "build/app/outputs/apk/release/app-arm64-v8a-release.apk#notes-arm64-v8a.apk" "commit-${{ github.sha }}"
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
